config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for(
    'User',
    at: 'auth',
    skip: [:omniauth_callbacks],
    controllers: {
      sessions: 'custom_sessions'
    }
  )

  resources :origins, only: [], param: :origin_name do
    member do
      get :sign_in, format: :json
      get :sign_up
      post :register, format: :json
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :v1, defaults: { format: :json } do
    resources :schools, only: :show, param: :school_id do
      collection do
        get :search
      end
      member do
        get :overview, :evolution, :ranking, :comparison, :histogram
        resources :questions, only: [:show, :index], param: :question_id
        resources :tags, only: :index
        resources :skills, only: :index
        resources :exams, only: :index
        resources :subjects, only: :index
      end
    end
    resources :users, only: [] do
      collection do
        get :current
      end
    end
    resources :groups, param: :group_id
  end
end

app/models/origin.rb
class Origin < ApplicationRecord
  has_many :users

  def rsa_public
    OpenSSL::PKey::RSA.new(public_key)
  end
end

app/controllers/origins_controller.rb
class OriginsController < ActionController::Base
  before_action :check_payload, :check_origin, :load_payload
  before_action :load_user, only: :sign_in
  before_action :check_params, :check_uniqueness, only: [:sign_up, :register]

  def sign_in
    credentials = user.create_new_auth_token
    render status: :ok,
           json: { credentials: credentials, redirect_to: autoload_path(credentials) }
  end

  def sign_up
    respond_to do |format|
      format.html { @user = origin.users.new(payload.permit(:name, :email)) }
      format.json do
        begin
          school = School.find(payload[:school_id])
          user = origin.users.new(payload.permit(:name, :email, :phone, :role))
          user.schools = [school]
          user.password = SecureRandom.hex(8)
          user.save!
          credentials = user.create_new_auth_token
          render status: :ok,
                 json: { credentials: credentials,
                         redirect_to: autoload_path(credentials) }
        rescue ActiveRecord::RecordNotFound
          render status: :bad_request, json: { message: 'School does not exists.' }
        rescue ActiveRecord::RecordInvalid
          render status: :unprocessable_entity, json: { message: 'Could not save user.' }
        end
      end
    end
  end

  def register
    @user = origin.users.new(user_params)
    @user.save!
    @redirect_to = autoload_path(@user.create_new_auth_token)
  rescue ActiveRecord::RecordInvalid
    render partial: 'refresh'
  end

  private

  attr_accessor :payload, :origin, :encrypted_payload, :user

  def autoload_path(credentials)
    request.base_url +
      "/autoload?credentials=#{URI.encode_www_form_component(credentials.to_json)}"
  end

  def user_params
    password = SecureRandom.hex(8)
    params.require(:user).permit(:phone, :role)
          .merge(payload.permit(:name, :email))
          .merge(school_ids_param)
          .merge({ password: password })
  end

  def school_ids_param
    schools = params.require(:user)[:schools]
    schools.blank? ? { school_ids: [] } : { school_ids: [schools] }
  end

  def check_uniqueness
    return if origin.users.where(email: payload[:email]).empty?
    respond_to do |format|
      format.html { to_lading }
      format.json { render status: :unprocessable_entity,
                           json: { message: 'User already exists.' } }
    end
  end

  def check_params
    respond_to do |format|
      format.js { }
      format.html do
        return if (['name', 'email'] - payload.keys).empty?
        to_lading
      end
      format.json do
        return if (['name', 'email', 'role', 'phone', 'school_id'] - payload.keys).empty?
        render status: :bad_request,
               json: { message: 'Parameters `name`, `email`, `role`, `phone` and '\
                                '`school_id` are required.' }
      end
    end
  end

  def load_user
    @user = origin.users.find_by!(email: payload[:email])
  rescue ActiveRecord::RecordNotFound
    respond_to do |format|
      format.html { to_lading }
      format.json do
        render status: :not_found, json: { message: 'No user with the given `email`.' }
      end
    end
  end

  def load_payload
    @payload, _ = JWT.decode(encrypted_payload, origin.rsa_public, 'RS256')
    @payload = ActionController::Parameters.new(@payload)
  rescue JWT::DecodeError
    respond_to do |format|
      format.html { to_lading }
      format.json do
        render status: :unauthorized, json: { message: 'Failed to read the payload.' }
      end
    end
  end

  def check_payload
    @encrypted_payload = params.require(:encrypted_payload)
  rescue ActionController::ParameterMissing
    respond_to do |format|
      format.html { to_lading }
      format.json do
        render status: :bad_request,
               json: { message: 'Parameter `encrypted_payload` is missing.' }
      end
    end
  end

  def check_origin
    @origin = Origin.find_by!(name: origin_name)
  rescue ActiveRecord::RecordNotFound
    respond_to do |format|
      format.html { to_lading }
      format.json do
        render status: :forbidden, json: { message: 'This `origin` is not allowed.' }
      end
    end

  end

  def to_lading
    redirect_to '/'
  end

  def origin_name
    params.require(:origin_name)
  end
end

app/views/origins/_refresh.js.erb
$("#new_user").html("<%= j render 'sign_up_form' %>");

$("#user_schools").select2({
  language: 'pt-BR',
  ajax: {
    url: "/v1/schools/search",
    dataType: 'json',
    delay: 250,
    data: function (params) {
      return {
        term: params.term
      };
    },
    processResults: function (data, params) {
      return {
        results: $.map(data, function (item) {
              return {
                  text: item.name,
                  id: item.id,
                  inep_code: item.inep_code
              };
          })
      };
    },
    cache: true
  },
  minimumInputLength: 1
});

$("#user_phone").mask("(99) 9999-9999?9").focusout(function (event) {
  var target, phone, element;
  target = (event.currentTarget) ? event.currentTarget : event.srcElement;
  phone = target.value.replace(/\D/g, '');
  element = $(target);
  element.unmask();
  if(phone.length > 10) {
      element.mask("(99) 99999-999?9");
  } else {
      element.mask("(99) 9999-9999?9");
  }
});

app/views/origins/_sign_up_form.html.erb
<%= simple_form_for @user, url: register_origin_url(@origin.name),
                           method: :post,
                           remote: true  do |f| %>
  <%= f.input :name, readonly: true %>
  <%= f.input :email, readonly: true %>
  <%= f.input :phone %>
  <%= f.input :role %>
  <%= f.input :schools, collection: @user.schools, selected: @user.school %>
  <%= f.hidden_field :encrypted_payload,
                     value: @encrypted_payload,
                     name: :encrypted_payload %>
  <%= f.submit id: :submit,
               value: 'Salvar Usuário',
               data: { disable_with: "Salvando..." } %>
<% end %>

app/views/origins/register.js.erb
window.location.replace('<%= @redirect_to %>');

app/views/origins/sign_up.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resultados ENEM</title>
    <%= csrf_meta_tags %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css"
          rel="stylesheet" />
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.min.js">
    </script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/pt-BR.js"></script>

    <style type="text/css">
      @import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300italic,400,400italic,600,600italic,700,700italic");
      body {
        font-family: 'Source Sans Pro', Arial, Helvetica, sans-serif;
        background: #E5376E;
        color: white;
        font-size: 13pt;
      }
      .main {
        width: 90%;
        max-width: 30rem;
        margin: 0 auto;
      }
      h1 {
        text-transform: uppercase;
        text-align: center;
        border-bottom: 1pt solid white;
        padding-bottom: 2rem;
      }
      #new_user {
        display: flex;
        flex-flow: column;
      }
      .input label {
        font-size: 0.9rem;
      }
      .input {
        display: flex;
        flex-flow: column;
        margin-bottom: 1.3rem;
      }
      .input input {
        background: #E5376E;
        border: 0.8pt solid #E5A3B8;
        padding: 0.8rem;
        color: white;
        border-radius: 4pt;
        font-size: 1rem;
        outline: none;
      }
      .input input:focus {
        border-color: white;
      }
      .input .error {
        font-size: 0.8rem;
        padding: 0.2rem;
        border-radius: 0 0 4pt 4pt;
        background: #E57995;
        border-top: 4pt solid #E57995;
        margin-top: -4pt;
        z-index: -1;
        position: relative;
      }
      #submit {
        padding: 1rem 3rem;
        background: white;
        color: #E5376E;
        text-transform: uppercase;
        font-weight: bold;
        font-family: 'Source Sans Pro', Arial, Helvetica, sans-serif;
        align-self: center;
        font-size: 1rem;
        border: 0.8pt solid white;
        border-radius: 4pt;
        cursor: pointer;
        transition: background-color ease 0.3s, color ease 0.3s;
      }
      #submit:hover {
        background-color: #E55988;
        color: white;
        font-stretch: semi-expanded;
      }
      .select2-selection {
        background: #E5376E !important;
        border-color: #E5A3B8 !important;
        font-size: 1rem;
      }
      .select2-selection, .select2-selection__rendered, .select2-selection__arrow {
        height: 2.6rem !important;
        line-height: 2.6rem !important;
        color: white !important;
      }
      .select2-results {
        color: #999;
      }
    </style>
  </head>
  <body>
    <div class="main">
      <h1>Complete seu cadastro</h1>
      <%= render 'sign_up_form' %>
    </div>
    <script type="text/javascript">
      $(document).ready(function () {
        $("#user_phone").mask("(99) 9999-9999?9").focusout(function (event) {
          var target, phone, element;
          target = (event.currentTarget) ? event.currentTarget : event.srcElement;
          phone = target.value.replace(/\D/g, '');
          element = $(target);
          element.unmask();
          if(phone.length > 10) {
              element.mask("(99) 99999-999?9");
          } else {
              element.mask("(99) 9999-9999?9");
          }
        });

        $("#user_schools").select2({
          language: 'pt-BR',
          ajax: {
            url: "/v1/schools/search",
            dataType: 'json',
            delay: 250,
            data: function (params) {
              return {
                term: params.term
              };
            },
            processResults: function (data, params) {
              return {
                results: $.map(data, function (item) {
                      return {
                          text: item.name,
                          id: item.id,
                          inep_code: item.inep_code
                      };
                  })
              };
            },
            cache: true
          },
          minimumInputLength: 1
        });
      });
    </script>
  </body>
</html>